// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Circulo2', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Circulo2', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect({ width: 1920, height: 1080 })
    {
      const element = await driver.findElement(By.css(".ant-col:nth-child(4) img"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".ant-col:nth-child(4) img")).click()
    await driver.findElement(By.id("register_radio")).click()
    await driver.findElement(By.id("register_radio")).sendKeys("-2")
    await driver.findElement(By.id("register_radio")).sendKeys(Key.ENTER)
    await driver.findElement(By.css(".ant-btn > span")).click()
    {
      const element = await driver.findElement(By.css(".ant-btn"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
  })
})
