// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Fact2', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Fact2', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect({ width: 1920, height: 1080 })
    await driver.findElement(By.css(".ant-col:nth-child(2) img")).click()
    await driver.findElement(By.id("register_numero")).click()
    await driver.findElement(By.id("register_numero")).sendKeys("-2")
    await driver.findElement(By.id("register_numero")).sendKeys(Key.ENTER)
    await driver.findElement(By.css(".ant-btn > span")).click()
    await driver.findElement(By.id("register_numero")).click()
    await driver.findElement(By.css(".ant-btn > span")).click()
  })
})
